name: Camel Quarkus Demo Projects CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '17', '21' ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build JDK ${{ matrix.java }}
        run: |
          for PROJECT_POM in $(find . -name pom.xml)
          do
            mvn clean verify -f ${PROJECT_POM} -ntp -B -Dnative -Dquarkus.native.container-runtime=docker -Dquarkus.native.builder-image.pull=missing
          done
